chore(tsc): change fontend target to es5
Error: Class constructor cannot be invoked without `new`

If we change server code to es5, it doesn't run.(because of forEach at
server/index.js)